name: Android
description: 'Build android'

runs:
  using: "composite"
  steps:
    - name: add release.keystore
      shell: bash
#      env:
#        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
#        MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}
#        MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}
#        MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
      run: |
        echo -n ${ANDROID_KEYSTORE_BASE64} | base64 -d > ./${CUSTOM_DIR}/android/app/release.keystore
        echo "MYAPP_UPLOAD_STORE_FILE=./release.keystore" >> ./${CUSTOM_DIR}/android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_PASSWORD=${MYAPP_UPLOAD_KEY_PASSWORD}" >> ./${CUSTOM_DIR}/android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_ALIAS=${MYAPP_UPLOAD_KEY_ALIAS}" >> ./${CUSTOM_DIR}/android/gradle.properties
        echo "MYAPP_UPLOAD_STORE_PASSWORD=${MYAPP_UPLOAD_STORE_PASSWORD}" >> ./${CUSTOM_DIR}/android/gradle.properties

    - name: build apk
      shell: bash
      run: |
        yarn android:get:release

    - name: Archive production apk
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: |
          ./android/app/build/outputs/**/*.apk

    - name: build aab
      shell: bash
      run: |
        yarn android:get:aab

    - name: add GOOGLE_API_KEY
      shell: bash
#      env:
#        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        echo ${GOOGLE_API_KEY} > GOOGLE_API_KEY.json

    - name: publish
      shell: bash
      run: |
        find ./${CUSTOM_DIR}/android/app/build/outputs/ -name "*.aab" | xargs -t npx @lad-tech/mobygp -k ./GOOGLE_API_KEY.json -a
