name: Development

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main

jobs:
  checker:
    uses:  ./.github/workflows/checker.yml
  android:
    needs: [checker]
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: install
        uses: ./.github/actions/install
      - name: android
        uses: ./.github/actions/android
