name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    uses: ./.github/workflows/install.yml
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20.11.x ]
    steps:
      - name: lint
        run: yarn lint:ci
