name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    - uses: ./.github/workflows/install.yml
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: lint
      run: yarn lint:ci
