name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    uses: ./.github/workflows/install.yml
  test:
    runs-on: ubuntu-latest
    steps:
    - name: jest
      run: yarn test:ci
